from pydantic import BaseModel, Field
from typing import List


class ReasoningResponse(BaseModel):
    """
    Final business decision generated by the AI.
    """

    decision: str = Field(
        ...,
        description="Final decision (e.g., GO, NO GO, REVIEW)"
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=100,
        description="Confidence score (0-100)"
    )

    reason: List[str] = Field(
        default_factory=list,
        description="Reasons supporting the decision"
    )

    actions: List[str] = Field(
        default_factory=list,
        description="Recommended next business actions"
    )